<a href="https://colab.research.google.com/github/MarcosVel/Deep-Learning/blob/master/RNNShapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from keras.layers import SimpleRNN, Input, Dense
from keras.models import Model

2023-05-22 15:05:30.115777: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-05-22 15:05:30.145855: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-22 15:05:30.547956: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


#### Things you should automatically know and have memorized
N = number of samples

T = sequence length

D = number of input features

M = number of hidden units

K = number of output units

In [ ]:
# make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [ ]:
# make an RNN
M = 5 # number of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

2023-05-22 15:05:31.230811: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-05-22 15:05:31.245901: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-05-22 15:05:31.246012: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [ ]:
# get the output
Yhat = model.predict(X)
print(Yhat)

1/1 [==============================] - 1s 653ms/step
[[-0.50148815 -0.36707485]]


2023-05-22 15:05:32.464332: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:637] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.layers[1].get_weights()

[array([[ 0.06567526, -0.04523861, -0.17955202, -0.11723137,  0.1117602 ],
        [ 0.77954334,  0.08555502, -0.25681758, -0.04786849,  0.49403495],
        [ 0.6635689 , -0.8584884 ,  0.02294368,  0.35041505, -0.6933144 ]],
       dtype=float32),
 array([[-0.41644752, -0.676678  , -0.32485887,  0.5118882 ,  0.03340117],
        [ 0.03617672, -0.127662  ,  0.6837192 ,  0.33595386, -0.63407934],
        [ 0.78009653, -0.00238311, -0.07937904,  0.5642642 ,  0.25835776],
        [-0.16547833, -0.18191043,  0.64826614, -0.0107041 ,  0.72052896],
        [ 0.43511975, -0.7019346 ,  0.02108831, -0.55371195, -0.10448463]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [ ]:
model.layers[1].get_weights()[0].shape

(3, 5)

In [ ]:
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [ ]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [ ]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  
  # important: assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[-0.50148814 -0.36707482]


In [ ]:
# how to calculte the output for multiple samples at once
X = np.random.randn(3, T, D) # 3 samples instead of 1

# get the output
Yhat = model.predict(X)
print(Yhat)

1/1 [==============================] - 0s 11ms/step
[[-0.3016907   0.842697  ]
 [ 0.29144785 -0.43728313]
 [ 0.19216278  0.7455376 ]]
